blog/urls.py
# -*- coding: utf-8 -*- 

from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
    url(r'^$', views.BlogView.as_view(), name='index'),
    url(r'^create/$', views.CreatePostView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/', views.UpdatePostView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/', views.DeletePostView.as_view(), name='delete'),
    url(r'(?P<pk>\d+)/', views.PostView.as_view(), name='post'),
)

bookshelf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bookshelf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^shelf/', include('diary.urls', namespace='shelf')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
)

diary/urls.py
from django.conf.urls import patterns, url

from diary import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index')
)

main/urls.py
# -*- coding: utf-8 -*- 

from django.conf.urls import patterns, url

from main import views

urlpatterns = patterns ('',
	url(r'^$', views.index, name='index'),
	url(r'^contacts', views.contacts, name='contacts'),
)

blog/models.py
# -*- coding: utf-8 -*- 

"""
Django models for bookshelf project blog application
"""

from django.db import models

class Post(models.Model):
	title = models.CharField(max_length=100)
	text = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.title + ' (%s)' % self.date

class Comment(models.Model):
	post = models.ForeignKey(Post)
	author = models.CharField(max_length=50)
	text = models.TextField()
	date = models.DateField(auto_now_add=True)

	def __unicode__(self):
		return self.post.__unicode__() + ' ' + self.author + ' ' + self.text[:99]

diary/models.py
# -*- coding: utf-8 -*- 

"""
Django models for bookshelf project diary application
"""

from django.db import models
from django.contrib.auth.models import AbstractUser

class Reader(AbstractUser):
	"""
	A little bit extended standard user model. Extensions allow to count 
	wished and read books. These people are reading books.
	"""
	wished = models.IntegerField(default=0)
	read = models.IntegerField(default=0)

class Writer(models.Model):
	"""
	Data clas which describes writers (those people, who are writing books).
	"""
	name1 = models.CharField(max_length=30, verbose_name="First name")
	name2 = models.CharField(max_length=30, blank=True, \
		verbose_name="Second name")
	name3 = models.CharField(max_length=30, blank=True, \
		verbose_name="Third name")
	surname = models.CharField(max_length=30)

	born = models.DateField()
	died = models.DateField(blank=True)
	bio = models.TextField(blank=True)

	works = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name1[0] + '. ' + self.surname

class Work(models.Model):
	"""
	'Work' is more general term for a book. This data class describes all works that
	are 
	"""
	author = models.ForeignKey(Writer)
	reader = models.ForeignKey(Reader)
	annotation = models.TextField(blank=True)

	title = models.CharField(max_length=100)

	theme = models.CharField(max_length=20)
	genre = models.CharField(max_length=20, blank=True)
	form = models.CharField(max_length=20, blank=True)

	day_wished = models.DateField()
	day_read = models.DateField(blank=True)
	times_read = models.IntegerField(default=0,)

	active = models.BooleanField(default=True)

class Response(models.Model):
	work = models.ForeignKey(Work)
	responser = models.ForeignKey(Reader)

	title = models.CharField(max_length=100)
	response_text = models.TextField()

	date = models.DateField(auto_now_add=True)

main/models.py
from django.db import models

# Create your models here.

blog/views.py
# -*- coding: utf-8 -*- 
import json

from django.utils import timezone
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from models import Post

class AjaxResponseMixin(object):
	"""
	Mixin to add AJAX support to a form.
	"""

	def render_to_json_response(self, context, **response_kwargs):
		data = json.dumps(context)
		response_kwargs['content-type'] = 'application/json'
		return HttpResponse(data, **response_kwargs)

	def form_invalid(self, form):
		response = super(AjaxResponseMixin, self).form_invalid(form)
		if self.request.is_ajax():
			return self.render_to_json_response(form.errors, status=400)
		else:
			return response

	def form_valid(self, form):
		response = super(AjaxResponseMixin, self).form_valid(form)
		if self.request.is_ajax():
			data = {
				'pk': self.object.pk,
			}
			return self.render_to_json_response(data)
		else:
			return response


class BlogView(AjaxResponseMixin, CreateView):
	template_name = 'blog/index.html'
	model = Post
	success_url = '/blog/'
	fields = ['title', 'text']

	def get_post_list(self):
		return Post.objects.order_by('-date')[:10]

	def get_context_data(self, **kwargs):
		context = super(BlogView, self).get_context_data(**kwargs)
		context['moment'] = timezone.now()
		context['post_list'] = self.get_post_list()
		return context

class PostView(DetailView):
	model = Post
	template_name = 'blog/post.html' 

class CreatePostView(CreateView):
	model = Post
	fields = ['title', 'text']

class UpdatePostView(UpdateView):
	model = Post
	fields = ['title', 'text']

class DeletePostView(DeleteView):
	model = Post
	success_url = reverse_lazy('index')

diary/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone

# Create your views here.

def index(request):
	return HttpResponse(str(timezone.now()))

main/views.py
# -*- coding: utf-8 -*- 

from django.shortcuts import render
from django.utils import timezone

# Create your views here.
context = {'moment': timezone.now()}

def index(request):
	return render(request, 'main/index.html', context)

def contacts(request):
	return render(request, 'main/contacts.html', context)

blog/templates/blog/index.html
{% extends "main/base.html" %}
{% load humanize %}
{% block title %}N.A.Y.:Blog{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<button type="button" class="btn btn-default" data-toggle="modal" data-target="#create-post"><i class="fa fa-pencil"></i> Write a post</button>

<div class="modal fade" id="create-post" tabindex="-1" role="dialog" aria-labelledby="create-post-label" aria-hidden="true">
   <div class="modal-dialog">
      <div class="modal-content">
      <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
         <h4 class="modal-title" id="create-post-label">Write a post</h4>
      </div>
      <form action="{% url 'blog:index' %}" method="post">
         {% csrf_token %}
         <div class="modal-body">
            {{ form.as_p }}
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save changes</button>
         </div>
      </form>
      </div><!-- /.modal-content -->
   </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% endif %}

{% if post_list %}

	{% for post in post_list %}
		<h3><a href="{% url 'blog:post' post.id %}">{{ post.title }}</a></h3>
		<p class="text-muted">{{ post.date|naturalday }}</p>
		{{ post.text|safe }}
		<hr>
	{% endfor %}

{% else %}
	<p>No posts are avaiable.</p>
{% endif %}


{% endblock %}

blog/templates/blog/post.html
{% extends "main/base.html" %}

{% block title %}N.A.Y.:{{post.title}}{% endblock %}

{% block content %}

{% load humanize %}

<h3>{{ post.title }}</h3>
{{ post.text|safe }}
<hr>
{{ post.date|naturalday }}

{% if user.is_authenticated %}
| <button type="button" class="btn btn-link">edit</button>
{% endif %}

{% endblock %}

blog/templates/blog/post_confirm_delete.html
post

blog/templates/blog/post_form.html
{% extends "main/base.html" %}

{% block title %}N.A.Y.:Create Post{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<form action="{% url 'blog:index' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit" class="btn btn-primary">Save changes</button>
</form>
{% else %}
<div class="alert alert-warning">Только для зарегистрированных пользователей.</div>
{% endif %}

{% endblock %}

main/templates/main/base.html
<!DOCTYPE HTML>

<HTML>

<Head>
	{% load staticfiles %}
	{% load humanize %}
	<meta charset="utf-8">
	<link rel="icon" type="image/png" href="{% static 'main/images/favicon.png' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/bootstrap/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/fontawesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/master.css' %}">
	<title>{% block title %}{% endblock %}</title>
</Head>

<Body>
	
	
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="navbar-inner">
			<a class="navbar-brand" href="{% url 'main:index' %}">N.A.Y.</a>
			<ul class="nav navbar-nav">
				<li>
					<a href="{% url 'main:index' %}">
						<i class="fa fa-home"></i>
						Main
					</a>
				</li>
				<li>
					<a href="{% url 'blog:index' %}">
						<i class="fa fa-cloud"></i>
						Blog
					</a>
				</li>
				<li>
					<a href="{% url 'main:contacts' %}">
						<i class="fa fa-envelope"></i>
						Contacts
					</a>
				</li>
			</ul>
			{% if user.is_authenticated %}
			<p class="navbar-text navbar-right">
				Signed in as {{ user.username }} 
			</p>
			{% endif %}
		</div>
	</div>
	<div class="row-fluid">
		{% if moment %}
		<div class="col-md-3 alert alert-info">
		
			<h4>Today</h4>
			The {{ moment|date:"j"|ordinal }} of {{ moment|date:"F Y"}}, {{ moment|date:"l" }} <br>
			The {{ moment|date:"z"|ordinal }} day of the year.

		</div>
		{% else %}
		<div class="col-md-2">
		</div>
		{% endif %}
		<div class="col-md-7">
			{% block content %}{% endblock %}
		</div>
	</div>
	<script type="text/javascript" src="{% static 'main/jquery-1.10.2.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/bootstrap/js/bootstrap.min.js' %}"></script>
</Body>

</HTML>

main/templates/main/contacts.html
{% extends "main/base.html" %}

{% block title %}N.A.Y.:Contacts{% endblock %}

{% block content %}
	<h3><i class="fa fa-male"></i> Нефёдов Александр</h3> 
	<i class="fa fa-map-marker"></i> Россия, Санкт-Петербург <br>
	<i class="fa fa-envelope-o"></i> nefedov.alexander91@yandex.ru <br>
	<i class="fa fa-phone"></i> +7(952)202-72-63 <br>
	<i class="fa fa-skype"></i> alexander.nefedov91 <br>
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block title %}N.A.Y.{% endblock %}

{% block content %}
	Мой контент.
{% endblock %}